using Allure.Commons;
using Atata;
using ATATA.Auto.Core.Meta;
using ATATA.Auto.Project.Data.Services;
using ATATA.Auto.Project.PageObjects.Pages;
using ATATA.Auto.Project.PageObjects.Steps;
using ATATA.Auto.Project.Utils;
using NUnit.Allure.Attributes;
using NUnit.Allure.Core;
using NUnit.Framework;

namespace ATATA.Auto.Tests.Traveler
{
    [AllureNUnit]
    [AllureSuite("Travelers")]
    [AllureDisplayIgnored]
    public class TravelerTest : BaseTest
    {
        [Test]
        [Category(TestType.Regression)]
        [Category(TestType.Smoke)]
        [AllureSeverity(SeverityLevel.critical)]
        [AllureTag(ComponentName.GTM_Travelers)]
        [AllureOwner(Author.ViktoriiaSkirko)]
        [AllureSubSuite("Create New Traveler")]
        [AllureFeature("Core")]
        public void AddNewTraveler()
        {
            var autogeneratedTravelerModel = TravelerService.GenerateTraveler();

            Go.To<SignInPage>()
               .Login<OverviewPage>(ConfigurationHelper.CurrentUser)
               .OpenReactUi()
               .MainMenu
               .Travelers
               .ClickAndGo()
               .CreateNewTraveler(autogeneratedTravelerModel)
               .Should.BeVisible()
               ;
        }
    }
}
