using Atata;
using ATATA.Auto.Core.Meta;
using ATATA.Auto.Project.Data.Services;
using ATATA.Auto.Project.PageObjects.Pages;
using ATATA.Auto.Project.PageObjects.Steps;
using ATATA.Auto.Project.Utils;
using NUnit.Framework;

namespace ATATA.Auto.Tests.Traveler
{
    public class TravelerTest : BaseTest
    {
        [Test]
        [Category(TestType.Regression)]
        [Category(TestType.Smoke)]
        public void AddNewTraveler()
        {
            var autogeneratedTravelerModel = TravelerService.GenerateTraveler();

            Go.To<SignInPage>()
               .Login<OverviewPage>(ConfigurationHelper.CurrentUser)
               .OpenReactUi()
               .MainMenu
               .Travelers
               .ClickAndGo()
               .CreateNewTraveler(autogeneratedTravelerModel)
               .Should.BeVisible()
               ;
        }
    }
}
